### ISSUE TITLE
エラーハンドリングを定義する

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/eccube-api4#149]
## FormType によるエラー

FormType によって出力されるエラーは、 Execution エラーに含まれる。
Query または Mutation 実行時に FormType のエラーが発生すると、data の出力はキャンセルされ、 errors のレスポンスを出力する。
エラーの対象は、 extensions.category に出力される。
Form の各フィールドに対するエラーは、 extensions.errorDetails に出力される。
エラーのレベルは extensions.level に出力される

出力例は以下の通り:

```json
{
  "errors": [
    {
      "message": "Form validation failed",
      "extensions": {
        "errorDetails": [
          {
            "field": "name02",
            "message": "入力されていません。"
          },
          {
            "field": "postal_code",
            "message": "数字で入力してください。"
          }
        ],
        "level": "Danger",
        "category": "FormValidation"
      },
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "entryCustomer"
      ]
    }
  ],
  "data": {
    "entryCustomer": null
  }
}
```

## 結果と共に出力するエラー

商品購入フローでは、商品の計算結果が変更された場合など、処理自体はエラーではないが、ユーザーの意図とは異なる結果になるために、画面に警告を出力する場合がある。
この場合は、 GraphQL の実行結果である data のレスポンスと共に errors のレスポンスを出力する。
エラーの対象は、 extensions.category に出力される。
エラーのレベルは extensions.level に出力される

```json
{
  "errors": [
    {
      "message": "一つ目の Warning です。",
      "extensions": {
        "level": "Warning",
        "category": "Global"
      }
    },
    {
      "message": "2つ目の Warning です。",
      "extensions": {
        "level": "Warning",
        "category": "Global"
      }
    }
  ],
  "data": {
    "entryCustomer": {
      "id": "135",
      "name01": "中津川",
      "name02": "陽一",
      "email": "1689822121.8617.kobayashi.yosuke@example.com",
      "postal_code": "7164940",
      "phone_number": "0965719050",
      "addr01": "八戸市",
      "addr02": "工藤町宮沢8-1-4",
      "Pref": {
        "id": "5",
        "name": "秋田県"
      },
      "Sex": {
        "id": "4",
        "name": "回答しない"
      },
      "Job": {
        "id": "2",
        "name": "コンサルタント"
      }
    }
  }
}
```

## Enums

- Level: `Danger|Warning|Info`
- Category: `Global|FormValidation`

## See Also

- https://spec.graphql.org/October2021/#sec-Handling-Field-Errors
- https://webonyx.github.io/graphql-php/error-handling/

**Comment by kiy0taka** [comment]
Level: Dangerは結果を返さない
Level: Warning/Infoは結果を返す

**Comment by nanasess** [comment]
参考
- https://techdozo.dev/graphql-error-handling/
- https://www.apollographql.com/docs/apollo-server/data/errors/?ref=escape.tech#error-codes

**Comment by nanasess** [comment]
こちらの実装は完了しているためクローズします。
残課題は #161 へ引き継ぎます
