### ISSUE TITLE
秘密鍵は不要？

### ISSUE THREAD

**Issue by kiy0taka** [EC-CUBE/eccube-api4#3]

**Comment by okazy** [comment]
できれば上の方針にしたい。
- 秘密鍵は不要
- 秘密鍵はDBに保存
- varに配置

**Comment by kiy0taka** [comment]
[必須パラメータになっている](https://github.com/trikoder/oauth2-bundle/blob/v3.x/DependencyInjection/Configuration.php#L54) ため、環境変数でファイルパスを定義するようにしました。
https://github.com/EC-CUBE/eccube-api4/blob/master/Resource/config/services.yaml#L2-L3

環境変数 `ECCUBE_OAUTH2_AUTHORIZATION_SERVER_PRIVATE_KEY` と `ECCUBE_OAUTH2_RESOURCE_SERVER_PUBLIC_KEY` がファイルパスでファイルが存在しない場合はキーペアを生成します。
