### ISSUE TITLE
商品在庫更新

### ISSUE THREAD

**Issue by kiy0taka** [EC-CUBE/eccube-api4#38]
# 概要
- 商品規格情報の在庫数を更新

パラメータ

| Name | type | Description |
| ---- | --------- | ------------- |
| code | string | 商品コード (必須) |
| stock | Int | 商品規格の在庫数 (在庫無制限が無効の場合は必須) |
| stock_unlimited | Boolean | 商品規格の在庫無制限 (必須) |

実行例

```graphql
# 在庫無制限ではない商品
mutation {
    editProductStock (
        code: "product-001"
        stock: 5
        stock_unlimited: false
    ) {
        code
        stock
        stock_unlimited
    }
}
```

```graphql
# 在庫無制限の商品
mutation {
    editProductStock (
        code: "product-002"
        stock_unlimited: true
    ) {
        code
        stock
        stock_unlimited
    }
}
```

商品コードで一意にならない場合は、エラーとする。

**Comment by okazy** [comment]
stock_unlimited のデフォルトをfalseにして以下でも更新可能にすべきか。

```graphql
# 在庫無制限ではない商品
mutation {
    editProductStock (
        code: "product-001"
        stock: 5
    ) {
        code
        stock
        stock_unlimited
    }
}
```

**Comment by okazy** [comment]
または、 `stock = null` でunlimitedとみなすUIも考えられる。

`ProductStock` には `stock_unlimited` が存在せず、無制限の時は `null` となる。

**Comment by okazy** [comment]
無制限は明示的に指定した方が良いとの意見をいただきましたので当初の仕様で実装します。
