### ISSUE TITLE
出荷ステータスの更新

### ISSUE THREAD

**Issue by kiy0taka** [EC-CUBE/eccube-api4#39]
- 注文出荷情報のステータスを更新

パラメータ

| Name | type | Description |
| ---- | --------- | ------------- |
| id | ID | 出荷ID (必須) |
| shipping_delivery_name | String | 配送方法 (変更する場合は必須) |
| shipping_date | String | 出荷日 (変更する場合は必須) |
| tracking_number | String | お問い合わせ番号 (変更する場合は必須) |
| note | String | 出荷用メモ欄 (変更する場合は必須) |

※注文情報に紐づく全ての出荷情報に出荷日が入れば、その注文情報が出荷済みとなる。

実行例

```graphql
mutation {
    editShippingStatus (
        id: 1
        shipping_delivery_name: "サンプル宅配"
        shipping_date: "2020-01-01"
        tracking_number: "tracking0123"
        note: "出荷しました。"
    ) {
        id
        shipping_delivery_name
        shipping_date
        tracking_number
        note
    }
}
```

**Comment by okazy** [comment]
こちら、受注ステータスを自由に変更可能なmutationではなく、出荷済みに変更する機能の想定です。

editShippingStatus は実態と合っていませんので、 updateShipped でどうかと思っています。

**Comment by okazy** [comment]
管理画面から出荷済みに変更する際には出荷完了メールを送信するかの選択ができます。
APIでも同じ要件が考えられますので、引数に `is_send_mail` を追加しようと思います。

また、 `shipping_date` は日付の取得の仕様に合わせ、 `2020-07-13T17:40:50+09:00` 形式にしようと思います。

**Comment by okazy** [comment]
想定処理

- 日付を入れる
- 全ての出荷に日付がはいいていたら、受注を出荷済みにする
- 出荷済みメールの送信をする（オプション）

**Comment by okazy** [comment]
「出荷用メモ欄」の更新は上書きではなく追記でもいい気がします
