### ISSUE TITLE
認可確認画面のデザインの改善

### ISSUE THREAD

**Issue by okazy** [EC-CUBE/eccube-api4#44]
認可確認画面にとりあえず情報を出している状態となっているので、最低限わかりやすいデザインに変えたい

![image (1)](https://user-images.githubusercontent.com/16895409/88136546-73170980-cc24-11ea-931e-008b830e89ac.png)

**Comment by nanasess** [comment]
許可しないボタンも欲しいです

**Comment by okazy** [comment]
許可しない場合はどのような処理が適切でしょうか？
リダイレクトURIに許可されなかったむねの情報を送信するとかでしょうか？
