### ISSUE TITLE
OAuth2.0 Authorization 管理画面ログイン

### ISSUE THREAD

**Issue by kiy0taka** [EC-CUBE/eccube-api4#5]

**Comment by nanasess** [comment]
- see https://github.com/EC-CUBE/ec-cube/pull/4474#issuecomment-588085587
- 上記実装を精査して、必要に応じて見直す
- 参考 http://openid-foundation-japan.github.io/openid-connect-core-1_0.ja.html#AuthRequest

**Comment by nanasess** [comment]
UserInterface(Member) と client_id の紐づけが必要。
