### ISSUE TITLE
ドキュメント作成

### ISSUE THREAD

**Issue by okazy** [EC-CUBE/eccube-api4#57]
ドキュメントページができました。
https://doc.ec-cube.net/eccube-api4/

ドキュメントに関する議論などをしていくためのIssueです。

関連
https://github.com/EC-CUBE/eccube-api4/pull/55

**Comment by okazy** [comment]
記載しておきたい内容

- インストール方法
- 利用方法
  - 構造がEntityの定義にそっている点や検索条件が簡易画面にそっている点など
- 拡張方法
  - QueryとMutationの追加方法
  - AllowListの追加方法
  - 検索条件のカスタマイズ方法
- AOuth2.0とGraphQLの説明（簡単な説明はあったほうが良いかと思う）

**Comment by okazy** [comment]
ドメインも今のままでも問題ないが、以下の方がより良いかと思いました。
https://doc4.ec-cube.net/api/
https://api.doc4.ec-cube.net/

**Comment by nanasess** [comment]
[こちらのような](https://doc.ec-cube.net/api_startup-guide#%E5%AE%9F%E8%A3%85%E3%82%B5%E3%83%B3%E3%83%97%E3%83%AB) 各言語の実装サンプルがあった方がよいかなと思います
